services:
  loadbalancer:
    environment:
      NGINX_UPSTREAM_SERVERS: |
        server cheer-tool-server-1:3000;

  db: 
    ports:
      - 15432:5432

  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    image: anicklaus/cheer-tool:dev
    env_file:
      - .server.dev.env
    deploy:
      replicas: 1
    volumes:
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json
      - ./server/src:/usr/src/app/src
      - ./server/dist:/usr/src/app/dist