const ERROR_CODES = {
  UNKNOWN_ERROR: "E000",
  PASSWORD_CHANGE_NOT_ALLOWED: "E001",
  REDUNDANT_ROUTING: "E002",
  SSO_REQUEST_FAILED: "E003",
  FEEDBACK_QUERY_FAILED: "E004",
  USER_INFO_QUERY_FAILED: "E005",
  CLUB_QUERY_FAILED: "E006",
  NOTIFICATION_QUERY_FAILED: "E006",
  CHOREO_QUERY_FAILED: "E006",
  LOGIN_FAILED: "E007",
  SSO_LOGIN_FAILED: "E007",
  REGISTRATION_FAILED: "E008",
  VERSION_QUERY_FAILED: "E009",
  USER_UPDATE_FAILED: "E010",
  CLUB_UPDATE_FAILED: "E011",
};

export default ERROR_CODES;
