name: Build and push docker mailproxy images

on:
  push:
    branches:
      - "main"
    paths:
      - "mailproxy/**"
      - ".github/workflows/docker-mailproxy-image.yml"
  workflow_dispatch:

jobs:
  docker-mailproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            anicklaus/cheer-tool-mailproxy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mailproxy
          file: ./mailproxy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Trigger watchtower
        uses: indiesdev/curl
        with:
          # The target URL
          # Required: true if custom-config is not set
          url: http://watchtower.home.andreasnicklaus.de/v1/update

          # Request timeout (milliseconds)
          # Default: 1000
          timeout: 60_000

          # The authentication using token
          # This will override the Authorization header, for example Authorization: Bearer QWxhZGRpbjpPcGVuU2VzYW1l
          bearer-token: ${{ secrets.WATCHTOWER_TOKEN }}

          # If it is set to true, it will show the response log in the GitHub UI
          # Default: false
          log-response: true
